#!/usr/bin/env bash
# _env-live.sh — common helper for writing the EC2 application env files.
#
# Two files, one schema
# ---------------------
# `.env.docker`  Plain KEY=VALUE, no quotes — Docker `--env-file` format.
#                Consumed by /etc/systemd/system/multiagent-{api,ui}.service
#                via `docker run --env-file /opt/multiagent/.env.docker` on
#                EC2 (deploy/terraform/modules/ec2/user_data.sh).
# `.env.live`    Bash-source-safe `KEY="value"` with backslash/quote/dollar/
#                backtick escapes. Intended for laptop dev:
#                    source .env && source .env.live
#                    cd api && bun run dev
#
# The `.env.docker` file is the source of truth — it's emitted from a single
# heredoc in `_emit_env_live_body()`, then `_quote_for_bash()` derives
# `.env.live` from it. Comments and blank lines pass through unchanged in
# both files.
#
# Required caller exports (`$VAR` referenced in the heredoc):
#   AGENT_CONFIG_REFRESH_TOKEN, MONGODB_URI, MONGODB_URI_PUBLIC,
#   ATLAS_DB_NAME, BEDROCK_KB_ID, AWS_REGION, EMBEDDINGS_PROVIDER,
#   VOYAGE_ENDPOINT, EMBEDDING_MODEL_ID_LINE, AGENTCORE_MEMORY_STORE_ID,
#   AGENTCORE_GATEWAY_URL, AGENTCORE_ORCHESTRATOR_ARN, SPECIALIST_IDS[],
#   CW_API_LOG_GROUP, CW_UI_LOG_GROUP, COGNITO_JWKS, COGNITO_POOL_ID,
#   COGNITO_CLIENT_ID, EC2_IP, OTEL_EXPORTER_OTLP_ENDPOINT (optional),
#   ENVIRONMENT, GIT_SHA (optional), OTEL_SAMPLE_RATIO (optional).
#
# Caller must also have sourced `_agents-common.sh` so `specialist_runtime_arn`
# is in scope.

if [[ -z "${REPO_ROOT:-}" ]]; then
  echo "_env-live.sh: REPO_ROOT is not set — source from a deploy script" >&2
  return 1 2>/dev/null || exit 1
fi

# ── Internal: convert .env.docker → .env.live (bash double-quoted) ───────────
# Reads stdin, writes stdout. KEY=value lines become KEY="value" with
# backslash, double-quote, dollar, and backtick escaped so bash double-quote
# parsing recovers the value verbatim. Comments / blanks pass through.
#
# Implemented in pure bash (no python/awk dependency) so the helper is safe
# to call from any deploy script on any host with bash 4+. Using `python3 -`
# with a heredoc here is a trap — the heredoc is silently dropped when stdin
# is already a pipe.
_quote_for_bash() {
  # Regex stored in a variable — `[[ str =~ $re ]]` is portable across all
  # supported bash versions. Inlining the pattern works in some bash builds
  # but BASH_REMATCH captures come back empty in others.
  local re='^([A-Za-z_][A-Za-z0-9_]*)=(.*)$'
  local line key val
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" =~ $re ]]; then
      key="${BASH_REMATCH[1]}"
      val="${BASH_REMATCH[2]}"
      val="${val//\\/\\\\}"
      val="${val//\"/\\\"}"
      val="${val//\$/\\\$}"
      val="${val//\`/\\\`}"
      printf '%s="%s"\n' "$key" "$val"
    else
      printf '%s\n' "$line"
    fi
  done
}

# ── Internal: heredoc producing the canonical .env.docker content ────────────
_emit_env_live_body() {
  local generator_label="$1"

  cat <<EOF
# EC2 mode — generated by ${generator_label} on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Embedding: ${EMBEDDING_LINE:-unknown}
# Tools:     MongoDB MCP direct AgentCore Runtime; Gateway for non-Mongo tools
# Format:    Docker --env-file (plain KEY=VALUE, no quotes, no escapes).
#            Consumed by /etc/systemd/system/multiagent-{api,ui}.service via
#            'docker run --env-file /opt/multiagent/.env.docker'.
# Companion: .env.live is the bash-source-safe variant (KEY="value", escaped)
#            for laptop dev: source .env && source .env.live && bun run dev.
ORCHESTRATOR_MODE=runtime
AGENT_CONFIG_REFRESH_TOKEN=${AGENT_CONFIG_REFRESH_TOKEN}

# MongoDB Atlas
MONGODB_URI=${MONGODB_URI}
# Public-SRV fallback for laptop-side tools (memory-recall-diagnostic.py,
# scenario tests, post-deploy-smoke). The API container itself uses MONGODB_URI
# (PrivateLink) for VPC-only egress.
MONGODB_URI_PUBLIC=${MONGODB_URI_PUBLIC}
MONGODB_DB=${ATLAS_DB_NAME}

# Bedrock
BEDROCK_KB_ID=${BEDROCK_KB_ID}
AWS_REGION=${AWS_REGION}

# Embedding — explicit provider switch from deploy.sh (strict mode, no silent fallback).
#   voyage  → VOYAGE_SAGEMAKER_ENDPOINT set, selected Voyage Marketplace model
#             EMBEDDING_MODEL_ID is intentionally NOT written (would enable
#             a forbidden Bedrock fallback if it leaked into the runtime).
#   titan   → VOYAGE_SAGEMAKER_ENDPOINT empty, Bedrock Titan v2 (deviation)
EMBEDDINGS_PROVIDER=${EMBEDDINGS_PROVIDER}
VOYAGE_SAGEMAKER_ENDPOINT=${VOYAGE_ENDPOINT}
${EMBEDDING_MODEL_ID_LINE}

# AgentCore — Memory store, Gateway, Agent runtimes (orchestrator + specialists)
AGENTCORE_MEMORY_STORE_ID=${AGENTCORE_MEMORY_STORE_ID}
AGENTCORE_GATEWAY_URL=${AGENTCORE_GATEWAY_URL}
AGENTCORE_ORCHESTRATOR_ARN=${AGENTCORE_ORCHESTRATOR_ARN}
# MongoDB MCP AgentCore Runtime ARN (consumed by the smoke trace_join check
# to discover the runtime's vended CloudWatch log group; the API itself
# only talks to AGENTCORE_GATEWAY_URL which fronts this runtime). Empty
# when no MCP runtime exists yet (e.g. ec2-less laptop deploys).
MONGODB_MCP_RUNTIME_ARN=${MONGODB_MCP_RUNTIME_ARN:-}
EOF

  # Append one AGENTCORE_<UPPER>_ARN per discovered specialist so that
  # agentcoreSpecialistArn() in api/src/adapters/agentcore-runtime.ts can
  # pick them up via the legacy fallback path. Works for any number of
  # specialists defined in config/agents/*.agent.md.
  local _spec_id _upper_id _spec_arn
  for _spec_id in "${SPECIALIST_IDS[@]:-}"; do
    _upper_id="$(printf '%s' "$_spec_id" | tr '[:lower:]-' '[:upper:]_')"
    _spec_arn="$(specialist_runtime_arn "$_spec_id")"
    [[ -n "$_spec_arn" ]] && echo "AGENTCORE_${_upper_id}_ARN=${_spec_arn}"
  done

  cat <<EOF

# Tool hosting — all agent MCP traffic goes through AgentCore Gateway. The
# Gateway target invokes the dedicated MongoDB MCP AgentCore Runtime.
SHORT_TERM_MEMORY_BACKEND=agentcore
PERSIST_CHAT_SESSIONS=1
MEMORY_TTL_DAYS=30

# Long-term memory fact extractor. Pinned to Claude Haiku 4.5 because the
# previous default (claude-3-5-haiku-20241022) is deprecated and silently
# AccessDenied on freshly granted Bedrock accounts. Override only if you
# have enabled a different tool-use-capable model in your account.
MEMORY_EXTRACTION_MODEL_ID=us.anthropic.claude-haiku-4-5-20251001-v1:0

# LTM / trace value gating — sourced from .env so flips are deploy-tracked
# (no SSH/SSM hand-editing of /opt/multiagent/.env.docker on EC2).
#   MEMORY_TRACE_VALUES=1 → raw fact strings in trace events. Default 0 = "<redacted>".
#   TRACE_PROMPT_BODY=1   → prompt.assembled.body attached (full system prompt).
#   TRACE_REDACT=1        → blanket redactDeep pass over every event payload.
MEMORY_TRACE_VALUES=${MEMORY_TRACE_VALUES:-0}
TRACE_PROMPT_BODY=${TRACE_PROMPT_BODY:-0}
TRACE_REDACT=${TRACE_REDACT:-0}

# CloudWatch (API + UI log groups; journald → CW agent on EC2 ships here)
CLOUDWATCH_LOG_GROUP=${CW_API_LOG_GROUP}
CLOUDWATCH_UI_LOG_GROUP=${CW_UI_LOG_GROUP}

# Cognito — JWT auth for the API. Always on; assertJwksAuthConfigured()
# refuses to boot the API without AUTH_JWKS_URI + AUTH_ISSUER
# (api/src/lib/jwt-verify.ts).
AUTH_JWKS_URI=${COGNITO_JWKS}
AUTH_ISSUER=https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_POOL_ID}
STREAMLIT_COGNITO_POOL_ID=${COGNITO_POOL_ID}
STREAMLIT_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}

# EC2 URLs
STREAMLIT_API_URL=http://${EC2_IP}:3000/

# OpenTelemetry — points Bun API + Streamlit UI at the local ADOT Collector
# sidecar (modules/adot-collector). The sidecar signs SigV4 outbound to the
# AWS X-Ray OTLP endpoint, so apps never need their own credentials for
# telemetry. When OTEL_EXPORTER_OTLP_ENDPOINT is empty (e.g.
# enable_adot_collector = false in Terraform), the Bun bootstrap falls back
# to in-process tracing only and the Streamlit auto-instrumentation no-ops
# gracefully.
OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://127.0.0.1:4318}
OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
OTEL_SERVICE_NAME=multiagent-api
OTEL_RESOURCE_ATTRIBUTES=service.namespace=multiagent,deployment.environment=${ENVIRONMENT:-dev},service.version=${GIT_SHA:-unknown}
OTEL_TRACES_SAMPLER=parentbased_traceidratio
OTEL_TRACES_SAMPLER_ARG=${OTEL_SAMPLE_RATIO:-1.0}
# Streamlit-side instrumentation hook (Python distro convention).
OTEL_PYTHON_LOG_CORRELATION=true
OTEL_PYTHON_LOG_FORMAT=%(asctime)s %(levelname)s [%(name)s] [trace_id=%(otelTraceID)s span_id=%(otelSpanID)s resource.service.name=%(otelServiceName)s] - %(message)s
EOF
}

# ── Public: write_env_live_files <generator_label> ───────────────────────────
# Writes $REPO_ROOT/.env.docker (Docker --env-file format, canonical) and
# $REPO_ROOT/.env.live (bash-source-safe variant) from the caller's exported
# state. Prints a status line on success.
write_env_live_files() {
  local generator_label="${1:-unknown}"
  local out_docker="$REPO_ROOT/.env.docker"
  local out_bash="$REPO_ROOT/.env.live"

  _emit_env_live_body "$generator_label" > "$out_docker"
  _quote_for_bash < "$out_docker" > "$out_bash"
  chmod 600 "$out_docker" "$out_bash" 2>/dev/null || true
  echo "  [env] wrote $(basename "$out_docker") (Docker --env-file) + $(basename "$out_bash") (bash-source-safe)"
}

# ── Public: sync_env_live_to_ec2 <instance_id> ───────────────────────────────
# Base64-encodes both .env.docker (canonical, used by Docker) and .env.live
# (bash-source convenience for SSM-shelled debugging) and ships them via SSM
# to /opt/multiagent/. Requires send_ssm_command_retry + wait_for_ssm_command_success
# from the caller's environment (defined in deploy-project.sh / deploy-api.sh).
sync_env_live_to_ec2() {
  local instance_id="$1"
  local docker_b64 bash_b64 sync_cmd_id sync_cmd

  [[ -f "$REPO_ROOT/.env.docker" ]] || { echo "sync_env_live_to_ec2: $REPO_ROOT/.env.docker missing — call write_env_live_files first" >&2; return 1; }
  [[ -f "$REPO_ROOT/.env.live"   ]] || { echo "sync_env_live_to_ec2: $REPO_ROOT/.env.live missing — call write_env_live_files first"   >&2; return 1; }

  docker_b64=$(base64 < "$REPO_ROOT/.env.docker" | tr -d '\n')
  bash_b64=$(base64 < "$REPO_ROOT/.env.live"   | tr -d '\n')

  # Single SSM RunShellScript invocation writes both files atomically. Keeping
  # them in one command minimises window where systemd could reload against a
  # mismatched pair.
  sync_cmd="echo '${docker_b64}' | base64 -d > /opt/multiagent/.env.docker"
  sync_cmd="${sync_cmd} && chmod 600 /opt/multiagent/.env.docker"
  sync_cmd="${sync_cmd} && echo '${bash_b64}' | base64 -d > /opt/multiagent/.env.live"
  sync_cmd="${sync_cmd} && chmod 600 /opt/multiagent/.env.live"

  sync_cmd_id=$(send_ssm_command_retry \
    "$instance_id" \
    "multiagent: sync env files (.env.docker + .env.live)" \
    "[\"${sync_cmd}\"]" \
    12) || { echo "Failed to send env-file sync command to EC2" >&2; return 1; }

  wait_for_ssm_command_success "$sync_cmd_id" "$instance_id" 24 \
    || { echo "env-file sync command failed on EC2" >&2; return 1; }

  echo "  [env] synced .env.docker + .env.live to /opt/multiagent/ on $instance_id"
}
